### ISSUE TITLE
People page: every author is co-author of themselves

### ISSUE THREAD

**Issue by sebgntr** [ir-anthology/ir-anthology#110]

**Comment by Asqiir** [comment]
Bug is fixed

**Comment by najtin** [comment]
This bug is still present on the site as the github pages repo has not been updated since March. 
There is no CD for automatic updates, because a manual process was explicitly requested.

**Comment by sebgntr** [comment]
Thanks, the bug was fixed in code, but not redeployed until now. The website is also currently not served from the master branch.
